import Link from "next/link";
import PageHeader from "@/components/ui/PageHeader";
import prisma from "@/lib/prisma";
import Badge from "@/components/ui/Badge";
import { formatDate } from "@/lib/date";
import Pagination from "@/components/ui/Pagination";
import QueryErrorState from "@/components/internal/QueryErrorState";
import EmptyState from "@/components/internal/EmptyState";
import PaywallPanel from "@/components/internal/PaywallPanel";
import { auth } from "@/lib/auth";
import { canAccessFeature, getUserPlan } from "@/lib/billing/access";
import { trackBoardViewServer } from "@/lib/analytics/track-board-server";

export const dynamic = "force-dynamic";

const boardAlertFindManyArgs = {
  include: {
    savedFilter: { select: { id: true, name: true } },
  },
} as const;

const boardAlertFindMany = () => prisma.boardAlertLog.findMany(boardAlertFindManyArgs);

type BoardAlertRow = Awaited<ReturnType<typeof boardAlertFindMany>>[number];

function severityVariant(s: string): "green" | "yellow" | "red" | "default" {
  if (s === "HIGH") return "red";
  if (s === "WARNING") return "yellow";
  if (s === "INFO") return "default";
  return "default";
}

export default async function AlertsPage({
  searchParams,
}: {
  searchParams: Promise<{ page?: string }>;
}) {
  const session = await auth();
  const plan = getUserPlan(session);
  if (!canAccessFeature(plan, "ALERTS")) {
    return (
      <div className="space-y-6">
        <PageHeader title="Board alerts" description="Spikes and changes from saved board filters." />
        <PaywallPanel
          feature="ALERTS"
          currentPlan={plan}
          title="Alerts are a Pro feature"
          description="Upgrade to log and review board filter spikes, deltas, and severity over time."
        />
      </div>
    );
  }

  await trackBoardViewServer("alerts", "/boards/alerts");
  const params = await searchParams;
  const page = Math.max(1, parseInt(params.page ?? "1", 10) || 1);
  const pageSize = 30;
  const skip = (page - 1) * pageSize;

  let items: BoardAlertRow[] = [];
  let total = 0;
  let error: string | null = null;

  try {
    const [rows, cnt] = await Promise.all([
      prisma.boardAlertLog.findMany({
        ...boardAlertFindManyArgs,
        orderBy: { createdAt: "desc" },
        skip,
        take: pageSize,
      }),
      prisma.boardAlertLog.count(),
    ]);
    items = rows;
    total = cnt;
  } catch (e) {
    error = e instanceof Error ? e.message : "Failed to load alerts.";
  }

  return (
    <div>
      <PageHeader
        title="Alerts"
        description="Alert log generated by scheduled saved filter evaluations (DB-only, no external notifications yet)."
        action={
          <Link href="/boards" className="text-sm text-muted hover:opacity-80">
            ← Boards
          </Link>
        }
      />

      {error ? (
        <QueryErrorState message={error} />
      ) : items.length === 0 ? (
        <EmptyState
          title="No board alerts yet"
          description="Saved filters evaluate on a schedule. When a rule spikes, Mulify logs it here with severity and deltas — ideal for weekly reviews."
          action={
            <Link
              href="/boards/saved-filters"
              className="rounded-lg border border-border bg-foreground px-4 py-2 text-sm font-medium text-background hover:opacity-90"
            >
              Create a saved filter
            </Link>
          }
        />
      ) : (
        <>
          <div className="rounded-lg border border-border bg-card overflow-x-auto shadow-sm">
            <table className="w-full text-sm min-w-[1180px]">
              <thead>
                <tr className="bg-surface-2 border-b border-border text-left">
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide">Created</th>
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide">Board</th>
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide">Filter</th>
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide">Severity</th>
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide text-right">
                    Matched
                  </th>
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide text-right">
                    Δ
                  </th>
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide">Title</th>
                  <th className="px-3 py-2.5 text-[11px] font-semibold text-muted uppercase tracking-wide">Message</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {items.map((a) => (
                    <tr key={a.id} className="hover:bg-surface-2/70">
                      <td className="px-3 py-2.5 text-xs text-muted whitespace-nowrap">{formatDate(a.createdAt)}</td>
                      <td className="px-3 py-2.5 text-xs text-muted">{a.boardType}</td>
                      <td className="px-3 py-2.5">
                        <Link href={`/boards/saved-filters`} className="text-sm font-medium text-foreground hover:opacity-80">
                          {a.savedFilter?.name ?? a.savedFilterId}
                        </Link>
                        <div className="text-[11px] text-muted-2 font-mono mt-0.5">{a.savedFilterId.slice(0, 10)}</div>
                      </td>
                      <td className="px-3 py-2.5">
                        <Badge label={a.severity} variant={severityVariant(a.severity)} />
                      </td>
                      <td className="px-3 py-2.5 text-right tabular-nums text-foreground">{a.matchedCount}</td>
                      <td className="px-3 py-2.5 text-right tabular-nums text-muted">{a.deltaCount}</td>
                      <td className="px-3 py-2.5 text-sm text-foreground">{a.title}</td>
                      <td className="px-3 py-2.5 text-xs text-muted max-w-[520px] truncate" title={a.message}>
                        {a.message}
                      </td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>
          <Pagination total={total} page={page} pageSize={pageSize} totalPages={Math.ceil(total / pageSize)} />
        </>
      )}
    </div>
  );
}

